### ISSUE TITLE
Deprecated version of FB API used

### ISSUE THREAD

**Issue by oshtefchuk** [ketanjawahire/Facebook.ApiClient#23]
Hi,
When I try to use Facebook.ApiClient
and call first request like
`ApiRequest.Create(ApiRequest.RequestType.Paged, "me/adaccounts", _client)`
I got "Facebook.ApiClient.Exceptions.FacebookOAuthException: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.2"

As I see, you supported up to 3.0 version. Could you plz implement v3.2 support?

Thanks for your useful solution

**Comment by ketanjawahire** [comment]
Hi @oshtefchuk, 
Thanks  for the issue report. I have been working on adding support for new api version. 
I will fix it & release new version soon.

**Comment by ketanjawahire** [comment]
Hi @oshtefchuk,

This issue seems to be fixed. 
I have added a new constructor overload that accepts api version as a parameter.
Download latest version 2.02 & you should be able to specify api version.
